name: Contributor Metrics in PSM
 
on:
  push:
    branches:
      - '**'
defaults:
   run:
     shell: bash
 
permissions:
   contents: write
   actions: read
 
env:
   ORG_NAME: "openpitrix"
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   TARGET_DATE: "2025-03-01T00:00:00Z"
jobs:
   Get-Metrics:
     runs-on: ubuntu-latest 
     timeout-minutes: 120
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
 
      #  - name: Initialize
      #    run: |
      #      GITHUB_USER_EMAIL= "racharlasputhnika27@gmail.com"
      #      GITHUB_USER_NAME="shivani-acr"
      #      pip install yq
      #      git config --global user.email "$GITHUB_USER_EMAIL"
      #      git config --global user.name "$GITHUB_USER_NAME"
 
       - name: Install jq
         run: sudo apt update && sudo apt install -y jq
       - name: Set up UTF-8 locale
         run: |
           sudo locale-gen en_US.UTF-8
           sudo update-locale LANG=en_US.UTF-8
       - name: List Repositories
         run: |
          page=1
          while :; do
            result=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100&page=${page}")
            repolist=$(echo "$result" | jq -r '.[]  | [.id,.name]')
            echo "$repolist"
            if [[ -z "$repolist" ]]; then
              break
            fi
            echo "$repolist" >> repo_list.txt
            page=$((page + 1))
          done
